// <auto-generated />
using System;
using JewelChitApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JewelChitApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251005130204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JewelChitApplication.Models.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("area_code");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area_name");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("area_type");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("integer")
                        .HasColumnName("customer_count");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pincode");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_areas_company_id");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("company_code");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_type");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("integer")
                        .HasColumnName("customer_count");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pincode");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.Property<string>("RelationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation_name");

                    b.Property<string>("RelationshipName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relationship_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerAddressInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address3");

                    b.Property<string>("Address4")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address4");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_address_info");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_address_info_customer_id");

                    b.ToTable("customer_address_info", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("primary_phone");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("secondary_phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_customer_contact_info");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_contact_info_customer_id");

                    b.ToTable("customer_contact_info", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocumentData")
                        .HasColumnType("text")
                        .HasColumnName("document_data");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_documents");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_documents_customer_id");

                    b.ToTable("customer_documents", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerOtherInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("aadhar_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pan_number");

                    b.Property<string>("ReferenceBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_other_info");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_other_info_customer_id");

                    b.ToTable("customer_other_info", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AadharVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("aadhar_verified");

                    b.Property<DateTime?>("AadharVerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("aadhar_verified_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("FingerprintVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("fingerprint_verified");

                    b.Property<DateTime?>("FingerprintVerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fingerprint_verified_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_verification");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_verification_customer_id");

                    b.ToTable("customer_verification", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.GoldLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdvanceInterestAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("advance_interest_amount");

                    b.Property<int>("AdvanceMonths")
                        .HasColumnType("integer")
                        .HasColumnName("advance_months");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DueMonths")
                        .HasColumnType("integer")
                        .HasColumnName("due_months");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("interest_amount");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("interest_rate");

                    b.Property<Guid>("ItemGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_group_id");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("loan_amount");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("loan_date");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("loan_number");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("maturity_date");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_payable");

                    b.Property<decimal>("ProcessingFeeAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("processing_fee_amount");

                    b.Property<decimal>("ProcessingFeePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("processing_fee_percent");

                    b.Property<string>("RefNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_number");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheme_id");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("series");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCalculatedValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_calculated_value");

                    b.Property<decimal>("TotalGrossWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_gross_weight");

                    b.Property<decimal>("TotalMaximumValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_maximum_value");

                    b.Property<decimal>("TotalNetWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_net_weight");

                    b.Property<int>("TotalQty")
                        .HasColumnType("integer")
                        .HasColumnName("total_qty");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_gold_loans");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("idx_gold_loans_area");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_gold_loans_customer");

                    b.HasIndex("ItemGroupId")
                        .HasDatabaseName("ix_gold_loans_item_group_id");

                    b.HasIndex("LoanDate")
                        .HasDatabaseName("idx_gold_loans_loan_date");

                    b.HasIndex("LoanNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_gold_loans_loan_number");

                    b.HasIndex("SchemeId")
                        .HasDatabaseName("ix_gold_loans_scheme_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_gold_loans_status");

                    b.HasIndex("AreaId", "Status")
                        .HasDatabaseName("idx_gold_loans_area_status");

                    b.ToTable("gold_loans", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.ItemGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("group_code");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name");

                    b.Property<string>("GroupNameTamil")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name_tamil");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_item_groups");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_item_groups_area_id");

                    b.ToTable("item_groups", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("item_code");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<Guid>("ItemGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_group_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNameTamil")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name_tamil");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_item_types");

                    b.HasIndex("ItemGroupId")
                        .HasDatabaseName("ix_item_types_item_group_id");

                    b.ToTable("item_types", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.JewelFault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AffectsValuation")
                        .HasColumnType("boolean")
                        .HasColumnName("affects_valuation");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FaultCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fault_code");

                    b.Property<string>("FaultName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fault_name");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fault_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ItemGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_group_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<decimal?>("ValuationImpactPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("valuation_impact_percentage");

                    b.HasKey("Id")
                        .HasName("pk_jewel_faults");

                    b.HasIndex("ItemGroupId")
                        .HasDatabaseName("ix_jewel_faults_item_group_id");

                    b.ToTable("jewel_faults", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.PledgedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CalculatedValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("calculated_value");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("GoldLoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("gold_loan_id");

                    b.Property<decimal>("GoldRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gold_rate");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("gross_weight");

                    b.Property<decimal?>("HallmarkGrossWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("hallmark_gross_weight");

                    b.Property<decimal?>("HallmarkNetWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("hallmark_net_weight");

                    b.Property<string>("HallmarkPurity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hallmark_purity");

                    b.Property<string>("Huid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("huid");

                    b.Property<string>("Images")
                        .HasColumnType("text")
                        .HasColumnName("images");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_type_id");

                    b.Property<string>("JewelFault")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jewel_fault");

                    b.Property<decimal>("MaximumValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_value");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("net_weight");

                    b.Property<Guid>("PurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("purity_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_pledged_items");

                    b.HasIndex("GoldLoanId")
                        .HasDatabaseName("idx_pledged_items_loan");

                    b.HasIndex("ItemTypeId")
                        .HasDatabaseName("idx_pledged_items_item_type");

                    b.HasIndex("PurityId")
                        .HasDatabaseName("idx_pledged_items_purity");

                    b.ToTable("pledged_items", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.Purity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ItemGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_group_id");

                    b.Property<int?>("Karat")
                        .HasColumnType("integer")
                        .HasColumnName("karat");

                    b.Property<string>("PurityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("purity_code");

                    b.Property<string>("PurityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purity_name");

                    b.Property<decimal>("PurityPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("purity_percentage");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_purities");

                    b.HasIndex("ItemGroupId")
                        .HasDatabaseName("ix_purities_item_group_id");

                    b.ToTable("purities", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.RateSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("GoldPurityRatePerGram")
                        .HasColumnType("numeric")
                        .HasColumnName("gold_purity_rate_per_gram");

                    b.Property<decimal>("GoldRatePerGram")
                        .HasColumnType("numeric")
                        .HasColumnName("gold_rate_per_gram");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal>("SilverPurityRatePerGram")
                        .HasColumnType("numeric")
                        .HasColumnName("silver_purity_rate_per_gram");

                    b.Property<decimal>("SilverRatePerGram")
                        .HasColumnType("numeric")
                        .HasColumnName("silver_rate_per_gram");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_rate_sets");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_rate_sets_area_id");

                    b.ToTable("rate_sets", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.Scheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AdvanceMonth")
                        .HasColumnType("integer")
                        .HasColumnName("advance_month");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CalculationBased")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("calculation_based");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("calculation_method");

                    b.Property<string>("CompoundingFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("compounding_frequency");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomizedStyle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customized_style");

                    b.Property<int?>("EmiTenure")
                        .HasColumnType("integer")
                        .HasColumnName("emi_tenure");

                    b.Property<int>("GraceDays")
                        .HasColumnType("integer")
                        .HasColumnName("grace_days");

                    b.Property<decimal>("InterestPercentAfterValidity")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_percent_after_validity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStdRoi")
                        .HasColumnType("boolean")
                        .HasColumnName("is_std_roi");

                    b.Property<Guid>("ItemGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_group_id");

                    b.Property<decimal>("MaxLoanValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_loan_value");

                    b.Property<decimal>("MaxMarketValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_market_value");

                    b.Property<int>("MinCalcDays")
                        .HasColumnType("integer")
                        .HasColumnName("min_calc_days");

                    b.Property<decimal>("MinLoanValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_loan_value");

                    b.Property<decimal>("MinMarketValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_market_value");

                    b.Property<int?>("PenaltyGraceDays")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_grace_days");

                    b.Property<decimal?>("PenaltyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("penalty_rate");

                    b.Property<decimal>("ProcessingFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("processing_fee_percent");

                    b.Property<bool>("ProcessingFeeSlab")
                        .HasColumnType("boolean")
                        .HasColumnName("processing_fee_slab");

                    b.Property<decimal>("ReductionPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("reduction_percent");

                    b.Property<decimal>("Roi")
                        .HasColumnType("numeric")
                        .HasColumnName("roi");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("scheme_code");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scheme_name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<int>("ValidityInMonths")
                        .HasColumnType("integer")
                        .HasColumnName("validity_in_months");

                    b.HasKey("Id")
                        .HasName("pk_schemes");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("idx_schemes_area");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_schemes_active");

                    b.HasIndex("ItemGroupId")
                        .HasDatabaseName("idx_schemes_item_group");

                    b.HasIndex("SchemeCode")
                        .IsUnique()
                        .HasDatabaseName("idx_schemes_code");

                    b.HasIndex("AreaId", "IsActive")
                        .HasDatabaseName("idx_schemes_area_active");

                    b.HasIndex("ItemGroupId", "IsActive")
                        .HasDatabaseName("idx_schemes_group_active");

                    b.ToTable("schemes", (string)null);
                });

            modelBuilder.Entity("JewelChitApplication.Models.Area", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_areas_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerAddressInfo", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithOne("AddressInfo")
                        .HasForeignKey("JewelChitApplication.Models.CustomerAddressInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_address_info_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerContactInfo", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithOne("ContactInfo")
                        .HasForeignKey("JewelChitApplication.Models.CustomerContactInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_contact_info_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerDocument", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_documents_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerOtherInfo", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithOne("OtherInfo")
                        .HasForeignKey("JewelChitApplication.Models.CustomerOtherInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_other_info_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelChitApplication.Models.CustomerVerification", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithOne("Verification")
                        .HasForeignKey("JewelChitApplication.Models.CustomerVerification", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_verification_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelChitApplication.Models.GoldLoan", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gold_loans_areas_area_id");

                    b.HasOne("JewelChitApplication.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gold_loans_customers_customer_id");

                    b.HasOne("JewelChitApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gold_loans_item_groups_item_group_id");

                    b.HasOne("JewelChitApplication.Models.Scheme", "Scheme")
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gold_loans_schemes_scheme_id");

                    b.Navigation("Area");

                    b.Navigation("Customer");

                    b.Navigation("ItemGroup");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("JewelChitApplication.Models.ItemGroup", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_groups_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("JewelChitApplication.Models.ItemType", b =>
                {
                    b.HasOne("JewelChitApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_types_item_groups_item_group_id");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("JewelChitApplication.Models.JewelFault", b =>
                {
                    b.HasOne("JewelChitApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jewel_faults_item_groups_item_group_id");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("JewelChitApplication.Models.PledgedItem", b =>
                {
                    b.HasOne("JewelChitApplication.Models.GoldLoan", "GoldLoan")
                        .WithMany("PledgedItems")
                        .HasForeignKey("GoldLoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pledged_items_gold_loans_gold_loan_id");

                    b.HasOne("JewelChitApplication.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pledged_items_item_types_item_type_id");

                    b.HasOne("JewelChitApplication.Models.Purity", "Purity")
                        .WithMany()
                        .HasForeignKey("PurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pledged_items_purities_purity_id");

                    b.Navigation("GoldLoan");

                    b.Navigation("ItemType");

                    b.Navigation("Purity");
                });

            modelBuilder.Entity("JewelChitApplication.Models.Purity", b =>
                {
                    b.HasOne("JewelChitApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purities_item_groups_item_group_id");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("JewelChitApplication.Models.RateSet", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rate_sets_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("JewelChitApplication.Models.Scheme", b =>
                {
                    b.HasOne("JewelChitApplication.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schemes_areas_area_id");

                    b.HasOne("JewelChitApplication.Models.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schemes_item_groups_item_group_id");

                    b.Navigation("Area");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("JewelChitApplication.Models.Customer", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("ContactInfo");

                    b.Navigation("Documents");

                    b.Navigation("OtherInfo");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("JewelChitApplication.Models.GoldLoan", b =>
                {
                    b.Navigation("PledgedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
